### ISSUE TITLE
Letsupgrade Assignment 1

### ISSUE THREAD

**Issue by TRHarsha** [LetsUpgrade/Blockchain-Essentials#11]
**Question  1: What is your understanding of Blockchain?**

The combination of distributed database and cryptography where the data is variable, unchangeable, immutable, Tamper proof 

 **Question  2: What is the core problem Blockchain trying to solve? **

Haking
Security 
Removing middle man

**Question  3: What are the few features which Blockchain will give you?**

Data safety 
Highly secured 
Decentralized 

 **Question  4: What all things does a Block contain? **

Block number 
Transactional records
Previous block record 
Mining key

**Question  5: How is the verifiability of Blockchain has been attained?**

We can cross check the data with the Previous finger print of the database and by this process we can find or verify the data

**Comment by prasad97** [comment]
Please submit it in the provided form only
