### ISSUE TITLE
Assignment1_Blockchain

### ISSUE THREAD

**Issue by csakshi007** [LetsUpgrade/Blockchain-Essentials#12]
Q1. What is your understanding of blockchain? 

       The blockchain is combination of distributed dataset and cryptography where data is unchangeable, tamper proof, immutable where there is more authenticity and security, and no middleman is required. 

Q2. What is core problem blockchain trying to solving? 

      Hacking 

      Authenticity and security 

      Need of middle man

      

Q3. What are the few features that blockchain will give you.?

      Decentralised 

      High security 

      No need of middle man

      Safety of data

Q4. What all the things that block contains? 

      Block number 

      Nounce

      Data

      Mining key

      Transactions and previous jey records 

Q5. How is variability of a blockchain has been attained? 

      The records on a blockchain are secured through cryptography. Every time transactions are conducted on a blockchain data will be sorted in a new block. But before the block must added to channel the data must be verified by another users.

**Comment by prasad97** [comment]
Please submit it in the provided form only
