### ISSUE TITLE
Day 1 assignment

### ISSUE THREAD

**Issue by ZackO7** [LetsUpgrade/Blockchain-Essentials#6]
Assignment *Blockchain* 
1) What is your understanding of Blockchain?
Ans: Blockchain is a combination of *Distributed Database* and *Cryptography*. In blockchain hacking is not possible at all. It provides *High security, Verifiable and Transparency*.

2) What is the core problem Blockchain trying to solve?
Ans:Blockchain Address the problem of data security and trust by making the ledger public.

3) What are the features which Blockchain will give you?
Ans: *Verifiable, Unchangeable, Tamper-proof and Immutable* Internet 2.0.

4) What all things does a Block contain? Ans: a)Block Number 
         b)Transaction Record 
         c)Previous Block Signature 
         d)Mining Key.

5) How is the verifiability of Blockchain has been attained?
Ans: Blockchain have the whole community in which everyone is working at the same time on the same data. So when anyone change anything in a data then all the other members of this community will tell that person to correct the mistakes in his/her data and all the other members of this community have same signature than this one member.

**Comment by prasad97** [comment]
Please submit it in the provided form only
